language: python
sudo: required
python:
  - "2.7"

env:
  global:
    - COVERALLS_SERVICE_NAME=travis-ci

script:
  - pip install -r requirements.txt
  - coverage run --source='.' manage.py test taric_books

after_success:
  - coveralls